CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 3
PRINT_FREQ: 10

DATASET:
  DATASET: signal
  ROOT: data/
#  TEST_SET: 'list/validation.lst'
#  TRAIN_SET: 'list/train.lst'
  TEST_SET: 'all_list/'
  TRAIN_SET: 'all_list/'
  NUM_CLASSES: 6
MODEL:
  NAME: ownmodel
  NUM_OUTPUTS: 2
  PRETRAINED: "output/signal/signal/checkpoint.pth.tar"
#  PRETRAINED: 'output/signal/signal/best.pt'

LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 800
  - 800
  BASE_SIZE: 800
#  BATCH_SIZE_PER_GPU: 16
  BATCH_SIZE_PER_GPU: 2
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
#  RESUME: false
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 800
  - 800
  BASE_SIZE: 800
  BATCH_SIZE_PER_GPU: 2
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: 'output/signal/signal/best.pt'
  OUTPUT_INDEX: 1
